const happyBirthdayDescription = [
  'On your special day, I want to wish you a lifetime of happiness, love, and success. Happy birthday!',
  'May this birthday be the start of a wonderful journey that leads you to an even more amazing future. Enjoy your day!',
  'Sending you my warmest wishes on your birthday. May this day bring you all the joy and happiness you deserve.',
  'Happy birthday to someone who brings so much love and light into the world. May your day be as amazing as you are!',
  'Wishing you a day filled with laughter, love, and unforgettable moments. Happy birthday!',
  'Cheers to another year of beautiful memories and exciting adventures. Happy birthday!',
  'May your birthday be a celebration of all the incredible things you bring into the lives of others. Enjoy your special day!',
  'Sending you a big birthday hug and lots of love. May your day be as wonderful as you are!',
  'On this special day, I want you to know how much you mean to me. Happy birthday, and may all your dreams come true!',
  `Here's to another year of laughter, love, and making beautiful memories. Happy birthday!`,
  'May your birthday be filled with sunshine, laughter, and cherished moments. Enjoy every minute of your special day!',
  'Happy birthday to an amazing friend who always brings joy and laughter into my life. Cheers to another fantastic year!',
  'Sending you my heartfelt wishes for a birthday filled with happiness, love, and endless blessings. Enjoy your day!',
  'Today is the perfect day to celebrate you and all the wonderful things you bring to the world. Happy birthday!',
  'May your birthday be a reminder of how much you are loved and appreciated. Wishing you a day full of joy and surprises!',
  `Here's to a year filled with exciting opportunities, incredible adventures, and dreams come true. Happy birthday!`,
  'You deserve all the love, happiness, and success in the world. Happy birthday to an extraordinary person!',
  'Sending you warm birthday wishes and a big slice of cake to celebrate your special day. Enjoy!',
  'May your birthday be the beginning of a new chapter filled with love, laughter, and endless possibilities. Happy birthday!',
  'Wishing you a day as amazing and unique as you are. Happy birthday to someone truly special!',
  'Happy birthday to someone who lights up every room they enter. May your day be filled with happiness and laughter!',
  'Sending you heartfelt birthday wishes and a truckload of cake! Enjoy your special day to the fullest!',
  'May your birthday bring you lots of laughter, love, and happiness. Cheers to another amazing year!',
  'Happy birthday to a truly wonderful person. May your day be as extraordinary as you are!',
  'Wishing you a fantastic birthday filled with love, adventure, and everything your heart desires.',
  'May your birthday be a joyful celebration of the amazing person you are. Have a blast!',
  'Sending you warm birthday hugs and good vibes. May your day be as incredible as you!',
  'Happy birthday to someone who brings sunshine and positivity into the lives of others. Enjoy your special day!',
  `Here's to another year of blessings, growth, and beautiful moments. Happy birthday!`,
  'On your birthday, I want you to know how grateful I am to have you in my life. You deserve all the happiness in the world.',
  'Wishing you a day filled with love, laughter, and cherished memories. Happy birthday!',
  'May your birthday be a reminder of how loved and appreciated you are. Enjoy every moment of your special day!',
  'Happy birthday to an amazing person who makes the world a better place with their presence. Cheers to you!',
  'Sending you warm birthday wishes and a big celebration in your honor. Enjoy your special day!',
  'May your birthday be the start of a fantastic year ahead. Wishing you success, happiness, and fulfillment!',
  'Happy birthday to a true gem of a person. May your day be as precious and remarkable as you are!',
  'Wishing you a day filled with delightful surprises, beautiful moments, and happy memories. Happy birthday!',
  'Sending you smiles, hugs, and lots of birthday love. May your day be absolutely fantastic!',
  `On your special day, I want to thank you for being an incredible friend. Happy birthday, and here's to many more!`,
  'May your birthday be a time of reflection, celebration, and joy. You deserve all the best things life has to offer!',
  'Wishing you a day filled with laughter, love, and dreams come true. Happy birthday!',
  'Happy birthday to a shining star! May your birthday sparkle with happiness and bring you closer to your dreams.',
  'Sending you warm wishes, hugs, and a sprinkle of birthday magic. Enjoy your special day to the fullest!',
  'May your birthday be a stepping stone to a year filled with love, success, and endless opportunities. Happy birthday!',
  'On your special day, I want you to know that you are loved, appreciated, and cherished. Happy birthday, dear friend!',
  'Happy birthday! May this day mark the beginning of a remarkable journey that leads you to an extraordinary future.',
  'Sending you warmest wishes on your special day. May your birthday be as wonderful as you are!',
  'Wishing you a birthday filled with laughter, love, and unforgettable moments. Enjoy every minute of it!',
  'On your birthday, I hope you are surrounded by loved ones who cherish and appreciate you just as much as I do.',
];

module.exports = { happyBirthdayDescription };
