const happyBirthdayTitle = [
  'Happy Birthday!',
  'Wishing You a Fantastic Birthday!',
  'Celebrate Your Special Day!',
  'Sending Birthday Joy Your Way!',
  'Have a Wonderful Birthday!',
  'May Your Birthday Be Filled with Happiness!',
  'Enjoy Your Special Day!',
  'Sending Birthday Wishes and Hugs!',
  `Here's to a Year of Adventures!`,
  'Cheers to Your Birthday!',
  'Wishing You a Year Full of Blessings!',
  'Happy Birthday to an Amazing Person!',
  'May All Your Birthday Dreams Come True!',
  'Sending Warm Birthday Wishes!',
  'Have a Blast on Your Birthday!',
  'Cheers to Another Year Around the Sun!',
  'Wishing You Love and Laughter on Your Birthday!',
  'May Your Birthday Bring You Joy!',
  'Enjoy Your Cake and Celebrate!',
  'Happy Birthday to Someone Special!',
  'Wishing You a Memorable Birthday!',
  `Here's to Another Year of Adventures!`,
  'May Your Birthday Sparkle with Fun and Excitement!',
  'Sending Birthday Smiles Your Way!',
  'Celebrate and Enjoy Your Birthday!',
  'Happy Birthday, Beautiful!',
  'Wishing You a Day Full of Surprises!',
  'May Your Birthday Be Filled with Love and Laughter!',
  `Here's to a Fantastic Year Ahead!`,
  'Happy Birthday to an Incredible Friend!',
  'Sending Birthday Blessings Your Way!',
  'May Your Dreams Take Flight on Your Birthday!',
  'Wishing You a Spectacular Birthday!',
  'Have a Joyous Birthday Celebration!',
  'Cheers to Your Special Day!',
  'Happy Birthday, Sunshine!',
  'May Your Birthday Bring Abundant Happiness!',
  'Sending Birthday Cheers and Good Vibes!',
  'Have an Amazing Birthday!',
  'Wishing You a Year Full of Smiles!',
  'Happy Birthday to the Best Person I Know!',
  'May Your Birthday Be Full of Pleasant Surprises!',
  'Enjoy Your Birthday to the Fullest!',
  'Sending You Warm Birthday Greetings!',
  `Have a Rockin' Birthday!`,
  'Wishing You a Day Filled with Magic and Joy!',
  'Happy Birthday, Superstar!',
  'May Your Birthday Sparkle with Love and Fun!',
  `Here's to a Bright and Beautiful Year!`,
  'Happy Birthday, Dear Friend!',
];

module.exports = { happyBirthdayTitle };