const goodMorningDescriptions = [
  'Rise and shine to embrace the day with enthusiasm.',
  'Every morning is an opportunity to make a positive difference.',
  'Start your day with a grateful heart and a positive mindset.',
  'Believe in yourself and make the most of this brand new day.',
  'Embrace the morning sun and let it ignite your inner fire.',
  'Today is a blank canvas; paint it with vibrant colors.',
  'The morning holds the promise of endless possibilities.',
  'Wake up with determination and go to bed with satisfaction.',
  'Each morning brings a chance to rewrite your story.',
  `Don't wait for the perfect morning; make it perfect with your actions.`,
  'The morning is your stage; step into the spotlight and shine.',
  'Every sunrise is a reminder of new beginnings and fresh starts.',
  'Seize the morning and let your dreams take flight.',
  'Mornings are the foundation for a day filled with achievements.',
  'Success starts with the first step you take in the morning.',
  `Greet the morning with a smile, for it's the first step to happiness.`,
  'Awaken your potential and conquer the morning with passion.',
  'The morning is your opportunity to create a life you love.',
  'A positive morning sets the tone for a positive day.',
  'Harness the energy of the morning to fuel your ambitions.',
  'Mornings are a gift; make the most of them with gratitude.',
  'Let the morning sun energize your spirit and illuminate your path.',
  'With each morning, you have a chance to rewrite your destiny.',
  'The morning is a reminder that you have another day to chase your dreams.',
  'Success starts with your mindset in the morning; believe in yourself.',
  'Wake up with purpose, and the morning will reward you.',
  'Make your morning routine a ritual for success and self-care.',
  'Mornings are a blank canvas; fill them with purpose and passion.',
  'The morning holds the key to unlocking your full potential.',
  'Rise with determination, conquer your morning goals, and celebrate your victories.',
  'Embrace the morning silence and find clarity in your thoughts.',
  'Each morning is a fresh opportunity to become a better version of yourself.',
  'Start your day with a positive affirmation and watch your life transform.',
  `The morning is your chance to rewrite yesterday's limitations.`,
  'Mornings are a reminder that you have the power to create your reality.',
  'Fuel your morning with inspiration and watch your day unfold beautifully.',
  'Embrace the morning stillness and let it center your mind and soul.',
  'Start your morning with gratitude, and abundance will follow.',
  'The morning is a canvas; paint it with purpose and passion.',
  'Awaken your inner champion and conquer the morning with confidence.',
  'Mornings are a gateway to endless possibilities and extraordinary achievements.',
  'Set your intentions in the morning, and the universe will conspire in your favor.',
  `The morning whispers, "You have the power to make today amazing."`,
  'Start your morning with a positive thought, and watch your day blossom.',
  'Mornings are a reminder that you are one step closer to your dreams.',
  'Embrace the morning calmness and let it guide you to success.',
  'Each morning is a gift; unwrap it with excitement and gratitude.',
  'Start your day with purpose, and the morning will reward your efforts.',
  'The morning is an invitation to live your life to the fullest.',
  'Greet the morning with open arms and a heart full of gratitude.',
  'Wake up with gratitude and let it set the tone for a positive day ahead.',
  'Every morning is a chance to be better than you were yesterday.',
  'Embrace the morning dew as a reminder of the freshness and beauty of life.',
  'Good morning! Today is another opportunity to make your dreams a reality.',
  'The morning sun is a gentle reminder that you have the power to rise and shine.',
  'In the morning, set your intentions and let them guide your actions throughout the day.',
  'Every sunrise is a reminder of the endless possibilities that lie before you.',
  'Good morning! Let your enthusiasm for life radiate in everything you do.',
  'The morning is a gift; cherish it and make the most of each precious moment.',
  'In the morning, choose positivity and watch how it transforms your day.',
  'Start your day with a grateful heart and watch as blessings multiply.',
  'Good morning! Believe in yourself and your ability to overcome any challenge.',
  'The morning holds the promise of a brand new chapter in your journey.',
  `In the morning, let go of yesterday's regrets and focus on today's opportunities.`,
  'Rise and shine with a smile, for happiness is contagious.',
  'Good morning! Embrace the day with open arms and an open mind.',
  'The morning air is filled with hope; breathe it in and let it inspire you.',
  'In the morning, nourish your body, mind, and soul for a balanced and fulfilling day.',
  'Start your day with a positive affirmation and set the tone for greatness.',
  'Good morning! Today is a blank canvas; paint it with vibrant colors of joy and success.',
  'Good morning! Rise with determination and go to bed with satisfaction.',
  'The morning is a blank canvas; paint it with purpose and passion.',
  'In the morning, set your intentions and let them guide your actions.',
  'Embrace the morning sun as a reminder of the warmth and possibilities of a new day.',
  'Each morning brings a fresh start; make it count and make it extraordinary.',
  'Good morning! Let your smile be a ray of sunshine that brightens the world.',
  'The morning is an invitation to live fully, love deeply, and pursue your dreams.',
  'In the morning, choose to be present and make every moment meaningful.',
  'Awake each morning with gratitude, for it is the key to a joyful and abundant life.',
  'Good morning! Today is a gift; unwrap it with enthusiasm and gratitude.',
  'The morning is a reminder that you have the power to shape your day and your destiny.',
  'In the morning, fuel your body, mind, and soul with positivity and nourishment.',
  'Embrace the morning breeze and let it awaken your senses to the beauty of life.',
  'Good morning! Be the reason someone smiles and feels inspired today.',
  'The morning is a precious gift; use it wisely and make it a masterpiece.',
  `In the morning, let go of yesterday's worries and embrace the limitless possibilities of today.`,
  'Start your day with a grateful heart, for it attracts more reasons to be thankful.',
  'Good morning! Trust yourself, believe in your abilities, and conquer your goals.',
  'The morning is a reminder to chase your dreams fearlessly and with unwavering determination.',
  'In the morning, greet the world with open arms and a heart full of love and kindness.',
  'Good morning! Today is a new beginning, embrace it with open arms.',
  'The morning holds endless possibilities; make the most of them.',
  'In the morning, let your determination be stronger than your doubts.',
  'Each morning is a chance to rewrite your story and create a better version of yourself.',
  `Good morning! Believe in yourself and you're halfway there.`,
  `The morning sun whispers, "You are capable of amazing things."`,
  'In the morning, set your intentions and let your actions speak louder than words.',
  'Rise and shine! Today is a blank page; write a story worth telling.',
  'The morning is a gift; use it wisely and make a positive impact.',
  'Good morning! Wake up, smile, and conquer the day with positivity.',
];

const goodAfternoonDescriptions = [
  'Harness the energy of the afternoon and conquer your goals.',
  'Make the most of the afternoon hours and let your light shine.',
  'Embrace the possibilities that the afternoon brings.',
  'In the afternoon, find inspiration in every moment.',
  'Stay focused and productive as the afternoon unfolds.',
  'Seize the afternoon and make it a stepping stone to success.',
  'Harness the power of the afternoon to accomplish great things.',
  'Take a moment to recharge and refuel in the afternoon.',
  'Maximize your potential in the afternoon and leave a lasting impact.',
  `Find joy and fulfillment in the afternoon's journey.`,
  'In the afternoon, embrace the challenges and turn them into opportunities.',
  'Stay motivated and determined as the afternoon progresses.',
  'Unlock your creativity and let it flourish in the afternoon.',
  `Embrace the afternoon's energy and let it propel you forward.`,
  'Make the afternoon count by taking intentional actions towards your goals.',
  'In the afternoon, let your passion fuel your drive.',
  'Stay committed to your dreams and aspirations throughout the afternoon.',
  `Find balance and harmony in the afternoon's hustle and bustle.`,
  `Harness the afternoon's momentum to achieve extraordinary results.`,
  'In the afternoon, let your perseverance overcome any obstacles.',
  'Stay focused and present as the afternoon unfolds its magic.',
  `Make the most of the afternoon's opportunities and make a difference.`,
  `Embrace the afternoon's potential and let it inspire you.`,
  'In the afternoon, believe in yourself and your abilities.',
  'Stay motivated and determined to achieve greatness in the afternoon.',
  'Unlock your full potential and unleash it in the afternoon.',
  `Embrace the afternoon's challenges and let them make you stronger.`,
  'In the afternoon, cultivate a positive mindset and watch your progress soar.',
  'Stay resilient and adaptable as the afternoon presents new circumstances.',
  'Make the afternoon memorable by embracing new experiences.',
  'In the afternoon, find solace in the pursuit of your passions.',
  'Stay driven and dedicated as the afternoon pushes you forward.',
  `Harness the afternoon's creativity and let it flow freely.`,
  'In the afternoon, let your determination overcome any setbacks.',
  'Stay focused and persistent as the afternoon unveils its opportunities.',
  'Make the afternoon remarkable by pursuing excellence in everything you do.',
  'In the afternoon, stay inspired and motivated towards your goals.',
  `Embrace the afternoon's rhythm and find your flow.`,
  'In the afternoon, let your actions speak louder than words.',
  'Stay enthusiastic and committed as the afternoon progresses.',
  `Maximize your productivity and make the most of the afternoon's potential.`,
  'In the afternoon, let your resilience shine through any challenges.',
  `Stay proactive and take initiative in the afternoon's endeavors.`,
  `Harness the afternoon's energy to create positive change.`,
  'In the afternoon, find strength in the pursuit of your dreams.',
  'Stay focused and disciplined as the afternoon demands your best.',
  'Make the afternoon count by embracing growth and learning.',
  'In the afternoon, let your passion guide your actions.',
  'Stay motivated and persistent as the afternoon tests your resolve.',
  `Embrace the afternoon's possibilities and make them your reality.`,
  `In the afternoon, find solace in the progress you've made so far.`,
  'Harness the energy of the afternoon to tackle challenges with renewed determination.',
  `The afternoon is a reminder to take a moment and appreciate how far you've come.`,
  'Make the most of the afternoon and let your passion fuel your productivity.',
  'In the afternoon, embrace the power of focus and watch your goals unfold.',
  'The afternoon sun is a beacon of motivation; let it guide you towards your aspirations.',
  'Embrace the opportunities that the afternoon brings and make them count.',
  'The afternoon is a reminder to stay committed to your dreams, no matter the obstacles.',
  'In the afternoon, celebrate your achievements, no matter how small they may seem.',
  'Seize the afternoon and make it a stepping stone to a brighter future.',
  'The afternoon is a chance to reevaluate your priorities and realign with your purpose.',
  'In the afternoon, let your determination shine through any setbacks.',
  `Embrace the afternoon's rhythm and find your flow in the tasks at hand.`,
  'The afternoon is a canvas for creativity; let your ideas blossom and flourish.',
  'In the afternoon, stay focused on your goals and watch how progress unfolds.',
  'Harness the momentum of the afternoon and let it carry you towards success.',
  'The afternoon is a reminder to pause, breathe, and appreciate the beauty of the present moment.',
  'In the afternoon, find inspiration in the achievements of others and let it motivate you.',
  'Embrace the challenges of the afternoon as opportunities for growth and learning.',
  'The afternoon is a reminder to stay true to your values and embrace authenticity.',
  'In the afternoon, find joy in the journey, not just the destination.',
  'Harness the energy of the afternoon and channel it into productive and meaningful actions.',
  'The afternoon is a reminder to stay focused and committed to your goals.',
  'Embrace the afternoon as an opportunity to make progress and leave a positive impact.',
  'In the afternoon, let your passion and dedication shine through every task you undertake.',
  'Good afternoon! Believe in yourself and your ability to overcome any challenges.',
  'The afternoon is a chance to recharge, reflect, and refocus for the remainder of the day.',
  'Make the most of the afternoon by staying present and fully engaged in each moment.',
  'In the afternoon, celebrate the progress you have made and the lessons you have learned.',
  'Embrace the challenges of the afternoon as opportunities for growth and self-improvement.',
  'The afternoon is a canvas for creativity; let your ideas flow and inspire innovation.',
  'In the afternoon, take a moment to appreciate how far you have come on your journey.',
  'Good afternoon! Reenergize yourself with positivity and let it propel you forward.',
  'The afternoon is a reminder to stay committed to your dreams, no matter the obstacles.',
  'In the afternoon, stay determined and resilient in the pursuit of your goals.',
  `Embrace the afternoon's energy and use it to make a positive impact on the lives of others.`,
  'The afternoon is a reminder that small steps taken consistently lead to significant results.',
  'In the afternoon, find inspiration in the achievements and successes of others.',
  'Embrace the challenges of the afternoon as opportunities to learn, grow, and evolve.',
  'The afternoon is a reminder to take breaks, recharge, and nurture your well-being.',
  'In the afternoon, stay focused and keep your eyes on the prize.',
  'Harness the energy of the afternoon and make progress towards your goals.',
  'The afternoon is a reminder to pause, breathe, and recharge.',
  'Embrace the challenges of the afternoon, for they lead to growth and resilience.',
  'In the afternoon, find inspiration in the small victories that pave the way to success.',
  'Good afternoon! Keep pushing forward, even if progress seems slow.',
  'The afternoon sun ignites a fire within; let it fuel your determination.',
  'In the afternoon, choose to be proactive and make things happen.',
  `Embrace the afternoon's rhythm and let it carry you towards achievement.`,
  'Good afternoon! Remember, every step forward counts, no matter how small.',
];

const goodNightDescriptions = [
  `Reflect on the day's accomplishments and find gratitude in the night.`,
  'Embrace the serenity of the night and let it rejuvenate your spirit.',
  'In the night, find solace in the stillness and let your dreams take flight.',
  'The night is a canvas for your imagination; paint it with dreams.',
  'End the day with a sense of fulfillment and pride in your efforts.',
  'In the night, find peace in the knowledge that tomorrow brings new possibilities.',
  'Let the night sky inspire you to reach for the stars and beyond.',
  'The night is a sanctuary for self-reflection and personal growth.',
  `In the night, let go of the day's worries and embrace tranquility.`,
  `Find comfort in the night's embrace and recharge your mind and body.`,
  'In the night, let go of what no longer serves you and make space for new beginnings.',
  'The night is a reminder that rest is essential for progress.',
  'Embrace the silence of the night and listen to the whispers of your soul.',
  'In the night, find clarity in your thoughts and set intentions for tomorrow.',
  `The night is an opportunity to release the day's burdens and find inner peace.`,
  'In the night, let gratitude fill your heart and guide you towards contentment.',
  `Find solace in the night's darkness and let it ignite your inner light.`,
  'In the night, surrender to the beauty of the present moment.',
  'The night is a gateway to new possibilities and fresh perspectives.',
  'In the night, let go of expectations and embrace the flow of life.',
  `Find inspiration in the night's stillness and let it fuel your dreams.`,
  'In the night, find comfort in the knowledge that you did your best today.',
  'The night is a reminder that tomorrow is a blank page; write your story with intention.',
  'In the night, allow yourself to rest and recharge for a brighter tomorrow.',
  `Embrace the night's gentle embrace and let it soothe your weary soul.`,
  'In the night, find solace in the stars and let their beauty guide your path.',
  'The night is a reminder that even in darkness, there is always a glimmer of light.',
  `In the night, release the day's tensions and welcome peace into your being.`,
  `Find stillness in the night's embrace and discover the depths of your inner strength.`,
  'In the night, let gratitude be your guiding star and illuminate your journey.',
  'The night is a sanctuary for self-care and nourishment of the soul.',
  'In the night, find comfort in the knowledge that every ending is a new beginning.',
  'Embrace the mysteries of the night and let them awaken your sense of wonder.',
  'In the night, find peace in the knowledge that you are exactly where you need to be.',
  'The night is a canvas for dreams; paint yours with courage and passion.',
  `In the night, let go of the day's mistakes and embrace forgiveness.`,
  `Find solace in the night's silence and let it guide you towards inner harmony.`,
  'In the night, release the need for control and trust in the unfolding of life.',
  'The night is a reminder to honor your need for rest and rejuvenation.',
  'In the night, let go of what no longer serves your growth and welcome transformation.',
  'Embrace the stillness of the night and allow it to nurture your soul.',
  'In the night, find peace in the knowledge that you are enough, just as you are.',
  'The night is a mirror reflecting the beauty of your dreams; never stop believing.',
  'In the night, let gratitude fill your heart and illuminate your path.',
  `Find solace in the night's embrace and let it heal your weary soul.`,
  'In the night, release the need for perfection and embrace the beauty of imperfection.',
  'The night is a sanctuary for self-reflection and inner growth.',
  `In the night, let go of the day's worries and trust in the process of life.`,
  'Embrace the magic of the night and let it inspire your dreams.',
  'In the night, find peace in the stillness and allow it to restore your spirit.',
  'In the night, find peace in the stillness and let it soothe your soul.',
  'Embrace the tranquility of the night and allow it to rejuvenate your spirit.',
  'The night is a canvas for dreams; let your imagination run wild.',
  `In the night, reflect on the day's blessings and find gratitude in every moment.`,
  'As the night falls, let go of worries and trust in the process of life.',
  'The night is a sanctuary for self-care; prioritize rest and nourishment.',
  'In the night, let your dreams guide you towards a future filled with possibilities.',
  'Embrace the serenity of the night and let it bring clarity to your thoughts.',
  'The night is a reminder to be gentle with yourself and practice self-compassion.',
  'In the night, release any tension and surrender to the peace that surrounds you.',
  'The night sky is a reminder of the vastness of the universe and the potential within you.',
  'In the night, find solace in the knowledge that tomorrow is a new day, full of opportunities.',
  'Embrace the silence of the night and listen to the whispers of your heart.',
  'The night is a time for introspection; reflect on your journey and celebrate your growth.',
  'In the night, find comfort in the stillness and allow it to replenish your energy.',
  `The night is a reminder to let go of the day's struggles and welcome peace into your being.`,
  'In the night, find solace in the beauty of the stars and let their light guide your path.',
  'Embrace the mysteries of the night and let them ignite your curiosity and wonder.',
  'The night is a canvas for self-reflection; take the time to reconnect with your true self.',
  'In the night, let gratitude fill your heart and pave the way for a peaceful sleep.',
  `In the night, let go of the day's worries and embrace tranquility.`,
  'Embrace the peace and stillness of the night to restore your mind, body, and soul.',
  'The night is a sanctuary for self-reflection and inner growth.',
  'In the night, find solace in the silence and allow it to rejuvenate your spirit.',
  'Let the night be a reminder that tomorrow is a new day, full of possibilities.',
  'Good night! Reflect on your blessings and go to sleep with a grateful heart.',
  'The night is a time for healing, both physically and emotionally.',
  'In the night, release the tensions of the day and surrender to serenity.',
  'Embrace the stillness of the night and allow it to bring you peace and clarity.',
  'The night is a canvas for dreams; let your imagination soar and chase your aspirations.',
  'In the night, find comfort in the knowledge that you have done your best today.',
  'Good night! Let go of the past and trust in the unfolding of your journey.',
  'The night is a reminder to practice self-care and prioritize your well-being.',
  'In the night, let gratitude fill your heart and bring you a sense of contentment.',
  'Embrace the darkness of the night and let it guide you towards inner wisdom.',
  'The night is a time for introspection and self-discovery; listen to your inner voice.',
  'In the night, find peace in the stillness and allow it to nourish your soul.',
  'Good night! Reflect on your accomplishments and go to sleep knowing you made a difference.',
  'The night is a reminder that even in the darkness, there is always a glimmer of hope.',
  'In the night, surrender your worries to the universe and trust in its divine guidance.',
  `In the night, release the day's worries and welcome tranquility.`,
  'Embrace the calm of the night and let it restore your mind and body.',
  'The night is a canvas for dreams; paint yours with hope and ambition.',
  'In the night, reflect on your blessings and find gratitude in every moment.',
  `Good night! Let go of what didn't serve you today and make space for tomorrow's possibilities.`,
  'The night sky holds the answers to your deepest questions; gaze up and find clarity.',
  'In the night, silence your mind and listen to the whispers of your heart.',
  'Embrace the stillness of the night and allow it to bring you peace.',
  'The night is a reminder to prioritize self-care and nurture your well-being.',
  'Good night! Rest your body, recharge your spirit, and wake up ready to conquer tomorrow.',
];

module.exports = { goodMorningDescriptions, goodAfternoonDescriptions, goodNightDescriptions };