const goodMorningTitles = [
  'Good morning, sunshine!',
  'Rise and shine!',
  'A bright start to your day',
  'Wishing you a fantastic morning',
  'Hello, new day!',
  'Start your day with a smile',
  'Sending morning blessings your way',
  'Embrace the morning vibes',
  'A refreshing morning to you',
  'Wake up to a world of possibilities',
  'Greet the day with open arms',
  'Good morning, beautiful souls',
  'May your morning be filled with joy',
  'Sunrise brings new hope',
  'Make today amazing',
  'Morning bliss awaits',
  'Welcome the day with gratitude',
  'Wishing you a peaceful morning',
  'Enjoy the serenity of morning',
  'Good morning, lovely people!',
  'Seize the day with enthusiasm',
  'The day holds endless opportunities',
  'Let the morning inspire you',
  'A brand new day to conquer',
  'Start your morning on a positive note',
  'Sending you morning blessings',
  'Have a fabulous morning',
  'Embrace the beauty of a new day',
  'Good morning, dear friends!',
  'May your day be filled with happiness',
  'Greet the morning with a grateful heart',
  'Welcome the day with open eyes',
  'Rise up and shine brightly',
  'Make your morning magical',
  'Sending you sunshine and smiles',
  'Good morning, world!',
  'Awake and ready for a great day',
  'Morning wishes for a wonderful day',
  'Carpe Diem - Seize the morning!',
  'A fresh start to an incredible day',
  'Begin your day with positivity',
  'Wishing you a blessed morning',
  'Good morning, fellow adventurers!',
  'May your morning be full of inspiration',
  'Greet the dawn with gratitude',
  'Unlock the potential of the morning',
  'A morning filled with possibilities',
  'Good morning, dreamchasers!',
  'Embrace the energy of the morning',
  'Start your day with a happy heart',
  'Rise and shine to a beautiful day',
  'Good morning, sunshine!',
  'A brand new day full of possibilities',
  'Start your day with a positive mindset',
  'Wishing you a morning filled with smiles',
  'Embrace the morning tranquility',
  'Good morning, world-changers!',
  'May your day be as radiant as the sunrise',
  'Sending you warm greetings for a great day',
  'Enjoy the beauty of the morning',
  'Wake up and be awesome!',
  'Good morning, dreamers and doers!',
  'May your coffee be strong and your day be productive',
  'Wishing you a blessed and blissful morning',
  'Greet the day with open arms and a grateful heart',
  'Start your day with a cup of positivity',
  'Good morning, champions!',
  'Every morning is a fresh start, embrace it',
  'Wishing you a day filled with laughter and love',
  'May your morning be as peaceful as a calm ocean',
  'Wake up, smile, and make the most of today',
  'Good morning, superheroes!',
  'May your day be productive and rewarding',
  'Embrace the morning energy and conquer your goals',
  'Sending you a virtual hug to start your day right',
  'Good morning, world-changers!',
  'Wishing you a day filled with positivity and success',
  'May your morning be filled with inspiration and creativity',
  'Start your day with a grateful heart and a positive mindset',
  'Good morning, rockstars!',
  'May your day be as bright as the morning sun',
  `Rise and shine, it's a brand new opportunity`,
  'Wishing you a day filled with love and happiness',
  'Embrace the morning silence and find your inner peace',
  'Good morning, warriors!',
  'May your day be filled with exciting adventures',
  'Wake up with determination and go to bed with satisfaction',
  'Wishing you a morning of endless possibilities',
  'Start your day with a smile and let your light shine',
  'Good morning, go-getters!',
  'May your day be as beautiful as a blooming flower',
  'Embrace the morning breeze and feel alive',
  'Sending you positive vibes for a fabulous day ahead',
  'Good morning, trailblazers!',
  'Wishing you a day of breakthroughs and accomplishments',
  'Wake up and chase your dreams with passion',
  'May your morning be filled with peace and serenity',
  'Embrace the morning silence and find clarity',
  'Good morning, unstoppable!',
  'Wishing you a day filled with inspiration and positive energy',
];

const goodAfternoonTitles = [
  'Embrace the Journey and Trust the Process',
  'Faith Over Fear: Conquer Your Doubts',
  'Seeking Strength in the Divine',
  'Believe in Miracles: They Happen Every Day',
  'Finding Purpose in Every Step',
  'Unleash Your Potential: Be Fearlessly You',
  'Letting Go and Letting God',
  `Rise Above Adversity: You're Stronger Than You Think`,
  'Gratitude: The Key to Abundance',
  'Harnessing the Power of Faith',
  'Dare to Dream Big: Nothing is Impossible',
  'Walking in Faith, Stepping in Blessings',
  'Embracing Change: Your Future Awaits',
  'Overcoming Obstacles: The Power Within',
  `Trusting God's Plan: Surrendering Control`,
  'The Light of Faith: Illuminating Your Path',
  'Shine Bright: Let Your Faith be Your Guide',
  'Finding Strength in Prayer',
  'Resilience: Bouncing Back and Moving Forward',
  `Embracing God's Grace: Forgiveness and Redemption`,
  `Cultivating Inner Peace: Trusting God's Timing`,
  'Navigating Storms: Finding Peace Amidst Chaos',
  `Hope in the Darkest Times: God's Promises Never Fail`,
  'Choose Love Over Hate: Embracing Unity',
  'Living a Life of Purpose: Impacting Others',
  'Stepping Out of Your Comfort Zone: Growth Begins There',
  'Embracing Your Unique Journey: Comparison is the Thief of Joy',
  `Finding Strength in Weakness: God's Power Made Perfect`,
  'Choosing Faith Over Doubt: Miracles Happen',
  'Living with Intention: Making Each Moment Count',
  'Letting Go of Past Regrets: Embracing Forgiveness',
  `Embracing God's Unconditional Love: You Are Enough`,
  'Awakening Your Soul: Connecting with the Divine',
  'Walking by Faith, Not by Sight',
  'Radiate Positivity: Be the Light in the World',
  'Embracing Your Divine Purpose: You Have a Calling',
  `Trusting God's Provision: Abundance Awaits`,
  `Faith as Your Anchor: Weathering Life's Storms`,
  'Unlocking Your Potential: Embrace Your Gifts',
  'Finding Peace in the Midst of Chaos',
  'Living a Life of Gratitude: Counting Your Blessings',
  'Courage Over Fear: Embrace Your Brave Heart',
  `Embracing God's Promises: A Future Full of Hope`,
  'Walking in Love: Compassion in Action',
  'The Power of Prayer: Communicating with the Divine',
  'Embracing Divine Guidance: Trusting Your Inner Voice',
  'Strength Through Unity: Together, We Can Overcome',
  'Faith in Action: Impacting Lives Through Love',
  `Awakening Your Soul's Purpose: Unleashing Your Potential`,
  'Finding Joy in the Journey: Gratitude as Your Guide',
  'Embracing the Power of Hope: Light Always Follows Darkness',
  `Faith as a Shield: Overcoming Life's Challenges`,
  'The Beauty of Resilience: Rising Stronger After Every Fall',
  'A Heart Full of Gratitude: Unlocking the Abundance Within',
  'Finding Peace in Solitude: Connecting with Your Inner Self',
  'The Strength of Forgiveness: Healing and Letting Go',
  'Trusting in Divine Timing: Patience as a Virtue',
  'Living with Purpose: Impacting the World Around You',
  'Faith Overcomes Fear: Stepping into the Unknown',
  'Embracing Imperfection: Celebrating Your Uniqueness',
  'The Power of Stillness: Finding Serenity in the Chaos',
  'Walking in the Footsteps of Faith: Leaving a Lasting Legacy',
  'Transforming Pain into Purpose: Your Story Matters',
  'Rise Above Negativity: Choosing Positivity Every Day',
  'Embracing the Power of Prayer: Communicating with the Divine',
  'Trusting the Journey: Embracing Detours and Setbacks',
  'The Miracle of Second Chances: Redemption and Renewal',
  'Cultivating a Heart of Compassion: Making a Difference',
  'Awakening Your Inner Warrior: Courage in the Face of Adversity',
  'Living in the Present Moment: Finding Joy in Now',
  `Faith as an Anchor: Standing Firm in Life's Storms`,
  'Embracing Your Authentic Self: Embodying Your Truth',
  'Finding Strength in Vulnerability: Embracing Your Flaws',
  'The Power of Unity: Together We Can Achieve Greatness',
  'Navigating Uncertainty with Faith: Trusting the Unknown',
  'Embracing Divine Guidance: Surrendering to a Higher Plan',
  'Unlocking the Gates of Abundance: Embracing a Prosperous Mindset',
  'Walking in Humility: Embracing Grace and Kindness',
  'Choosing Joy: Cultivating a Positive Outlook on Life',
  'Embracing the Journey of Self-Discovery: Unveiling Your True Potential',
  'Living with Intention: Creating a Life that Aligns with Your Values',
  `The Power of Gratitude: Appreciating Life's Blessings`,
  'Embracing Change: Stepping Outside Your Comfort Zone',
  `Finding Peace in Nature: Connecting with God's Creation`,
  'The Strength of Faith: Overcoming Doubt and Uncertainty',
  'Awakening Your Inner Light: Illuminating the World',
  'Embracing the Miracle of Life: Celebrating Every Breath',
  'Living with Compassion: Extending Love to All',
  'Finding Balance in the Chaos: Nurturing Mind, Body, and Spirit',
  'The Gift of Forgiveness: Freeing Yourself from Resentment',
  `Embracing Divine Timing: Trusting the Universe's Plan`,
  'Cultivating Resilience: Turning Setbacks into Comebacks',
  'Embracing Your Inner Child: Rediscovering Joy and Wonder',
  'The Power of Faith: Moving Mountains with Belief',
  'Finding Peace in Surrender: Letting Go and Letting God',
  'Living with Gratitude: Appreciating the Simple Pleasures',
  'Embracing the Power of Love: Healing Hearts and Souls',
  'Walking the Path of Purpose: Making a Meaningful Impact',
  'The Beauty of Unity: Celebrating Diversity and Inclusion',
  'Embracing the Divine Within: Connecting with Your Spiritual Essence',
];

const goodNightTitles = [
  'Good evening, everyone!',
  'Wishing you a peaceful night',
  'Embrace the tranquility of the night',
  'Nighttime blessings coming your way',
  'Enjoy the beauty of the night',
  'Sending you moonlight and stars',
  'Wishing you a restful night',
  'Goodnight, dear friends!',
  'May your night be filled with dreams',
  `Find serenity in the night's embrace`,
  'Bask in the calmness of the night',
  'Nighttime whispers of peace and love',
  'Sending you peaceful vibes tonight',
  'Goodnight, beautiful souls!',
  'Let the night be your sanctuary',
  'Find solace in the stillness of the night',
  'Embrace the magic of the night',
  `Wishing you a rejuvenating night's sleep`,
  'Goodnight, lovely individuals!',
  'Discover the enchantment of the night',
  'Savor the quietude of the night',
  'Wrap yourself in the comfort of the night',
  'Sending you gentle dreams tonight',
  'Goodnight, dear ones!',
  'Find peace in the darkness of the night',
  'Sending you tranquility and calm',
  'Relax and unwind under the night sky',
  'Goodnight, moonlight!',
  'Embrace the stillness of the night',
  'Let the night inspire you',
  'Wishing you a night filled with happiness',
  'Goodnight, beloved friends!',
  'Find solace in the embrace of the night',
  'Discover the beauty of the starlit night',
  'Rest and recharge for a new day',
  'Sending you peaceful slumber',
  'Goodnight, world!',
  'Wrap yourself in the serenity of the night',
  'Enjoy the tranquility of the nighttime hours',
  'Wishing you sweet dreams',
  'Goodnight, fellow dreamers!',
  'Find inspiration in the beauty of the night',
  'Let the night heal your soul',
  `Dream peacefully under the night's canvas`,
  'Goodnight, dear ones!',
  'Find comfort in the stillness of the night',
  'Rest and relax for a brighter tomorrow',
  'Sending you peaceful thoughts before sleep',
  'Goodnight, amazing individuals!',
  'May your night be filled with peace and contentment',
  'Goodnight, moonlight!',
  'Wishing you sweet dreams and a restful night',
  'Embrace the calmness of the night',
  'May the night bring you peace and tranquility',
  'Goodnight, lovely souls!',
  'Dream peacefully under the starry sky',
  'Sending you peaceful thoughts for a serene night',
  'Wrap yourself in the comfort of the night',
  'Goodnight, beautiful dreamers!',
  'May your night be filled with bliss and contentment',
  'Embrace the stillness of the night and find serenity',
  'Wishing you a night of deep and rejuvenating sleep',
  'Goodnight, dear friends!',
  'Find solace in the quietude of the night',
  'May your dreams be filled with happiness and love',
  `Surrender to the night's embrace and let go`,
  'Goodnight, peaceful souls!',
  'Find comfort in the gentle embrace of the night',
  'May the night sky inspire and guide your dreams',
  'Embrace the magic of the night and let your imagination soar',
  'Goodnight, dear ones!',
  'Find peace in the stillness of the night',
  'May your dreams be filled with hope and possibilities',
  'Wishing you a night of restorative rest and relaxation',
  'Goodnight, beautiful hearts!',
  'Savor the tranquility of the night and recharge your soul',
  'May the night wrap you in its soothing embrace',
  'Embrace the silence of the night and find inner peace',
  'Goodnight, beloved friends!',
  'Find solace in the serenity of the moonlit night',
  'May your dreams be filled with joy and inspiration',
  'Wishing you a night of sweet dreams and gentle slumber',
  'Goodnight, precious souls!',
  `Surrender to the night's magic and let it guide your dreams`,
  'May the stars shine brightly upon your peaceful night',
  'Embrace the stillness of the night and let go of the day',
  'Goodnight, cherished ones!',
  'Find comfort in the softness of the night and let your worries fade',
  `May your dreams be a reflection of your heart's desires`,
  'Wishing you a night of deep relaxation and rejuvenation',
  'Goodnight, radiant souls!',
  'Savor the tranquility of the moonlit night and find serenity',
  'May the night whisper secrets of serenity and inspiration',
  'Embrace the silence of the night and find solace within',
  'Goodnight, extraordinary beings!',
  'Find peace in the quietude of the night and let it heal your soul',
  'May your dreams be filled with love and happiness',
  'Wishing you a night of undisturbed and blissful sleep',
  'Goodnight, shining stars!',
  `Surrender to the night's embrace and let it rejuvenate your spirit`,
];

module.exports = { goodMorningTitles, goodAfternoonTitles, goodNightTitles };