const refranesBuenasTardes = [
  'Que tengas una tarde tan bonita como tú.',
  'La tarde es un buen momento para reflexionar.',
  'Que la tarde te traiga alegría y felicidad.',
  'Una tarde bien aprovechada, es una tarde bien vivida.',
  'La tarde es una oportunidad para hacer cosas nuevas.',
  'Que la tarde te traiga tantas bendiciones como las estrellas del cielo.',
  'Una tarde llena de sol, es una tarde llena de vida.',
  'Que tengas una tarde de paz y armonía.',
  'Disfruta de la tarde como si fuera el último día de tu vida.',
  'Que la tarde te traiga dulces sorpresas.',
  'La tarde es un momento perfecto para estar en paz contigo mismo.',
  'Que la tarde te traiga la calma que necesitas.',
  'En la tarde, los problemas parecen más pequeños.',
  'Que la tarde te traiga momentos inolvidables.',
  'La tarde es un buen momento para pensar en todo lo que tienes.',
  'Que la tarde te traiga nuevas oportunidades.',
  'La tarde es un buen momento para tomar un descanso.',
  'Que la tarde te traiga la inspiración que necesitas.',
  'La tarde es un buen momento para ser agradecido por todo lo que tienes.',
  'Que la tarde te traiga la felicidad que mereces.',
  'La tarde es el mejor momento para compartir con amigos y familia.',
  'Que la tarde te traiga el amor que buscas.',
  'La tarde es un buen momento para ser feliz.',
  'Que la tarde te traiga la paz que necesitas.',
  'La tarde es el mejor momento para relajarse y olvidar los problemas.',
  'Que la tarde te traiga la tranquilidad que mereces.',
  'La tarde es un buen momento para estar en armonía con la naturaleza.',
  'Que la tarde te traiga la serenidad que necesitas.',
  'La tarde es el mejor momento para disfrutar de la vida.',
  'Que la tarde te traiga la amistad que mereces.',
  'La tarde es un buen momento para sonreír y ser feliz.',
  'Que la tarde te traiga la alegría que necesitas.',
  'La tarde es el mejor momento para ser agradecido por todo lo que tienes.',
  'Que la tarde te traiga la esperanza que necesitas.',
  'La tarde es un buen momento para disfrutar de la belleza de la vida.',
  'Que la tarde te traiga la luz que necesitas.',
  'La tarde es el mejor momento para perdonar y dejar ir el pasado.',
  'Que la tarde te traiga la sabiduría que necesitas.',
  'La tarde es un buen momento para abrazar a los que amas.',
  'Que la tarde te traiga la gratitud que mereces.',
  'La tarde es el mejor momento para ser feliz y estar en paz.',
  'Que la tarde te traiga la energía que necesitas.',
  'La tarde es un buen momento para meditar y encontrar la paz interior.',
  'Que la tarde te traiga la fuerza que necesitas.',
  'Una tarde sin sonrisa es una tarde perdida',
  'El sol siempre brilla después de una tarde lluviosa',
  'Que tengas una tarde llena de alegría y bendiciones',
  'Las mejores cosas de la vida suceden en la tarde',
  'Las tardes son como la vida, un hermoso atardecer es su recompensa',
  'La tarde es el momento perfecto para reflexionar sobre los logros del día',
];

module.exports = refranesBuenasTardes;
