const dailyQuotes = [
  'The future belongs to those who believe in the beauty of their dreams. - ***Eleanor Roosevelt***',
  'Success is not final, failure is not fatal: It is the courage to continue that counts. - ***Winston Churchill***',
  `Your time is limited, don't waste it living someone else's life. - ***Steve Jobs***`,
  `Believe you can and you're halfway there.' - ***Theodore Roosevelt***`,
  'The only way to do great work is to love what you do. - ***Steve Jobs***',
  'The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - ***Mark Zuckerberg***',
  `I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - ***Jimmy Dean***`,
  `Don't watch the clock; do what it does. Keep going. - ***Sam Levenson***`,
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  'The harder the conflict, the greater the triumph. - ***George Washington***',
  'Dream big and dare to fail. - ***Norman Vaughan***',
  'The best way to predict the future is to create it. - ***Peter Drucker***',
  'Success is not the key to happiness. Happiness is the key to success. - ***Albert Schweitzer***',
  'In the middle of every difficulty lies opportunity. - ***Albert Einstein***',
  'The secret of getting ahead is getting started. - ***Mark Twain***',
  `Don't be afraid to give up the good to go for the great. - ***John D. Rockefeller***`,
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - ***Christian D. Larson***',
  'Success is not in what you have, but who you are. - ***Bo Bennett***',
  'If you want to achieve greatness, stop asking for permission. - ***Anonymous***',
  'The only person you are destined to become is the person you decide to be. - ***Ralph Waldo Emerson***',
  'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - ***Steve Jobs***',
  'I find that the harder I work, the more luck I seem to have. - ***Thomas Jefferson***',
  'The best revenge is massive success. - ***Frank Sinatra***',
  `Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - ***Roy T. Bennett***`,
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  `Don't be afraid to stand for what you believe in, even if that means standing alone. - ***Andy Biersack***`,
  'Success usually comes to those who are too busy to be looking for it. - ***Henry David Thoreau***',
  'You are never too old to set another goal or to dream a new dream. - ***C.S. Lewis***',
  'If you are not willing to risk the usual, you will have to settle for the ordinary. - ***Jim Rohn***',
  'The only way to do great work is to love what you do. - ***Steve Jobs***',
  'Life is 10% what happens to us and 90% how we react to it. - ***Charles R. Swindoll***',
  'The road to success and the road to failure are almost exactly the same. - ***Colin R. Davis***',
  `If you really want to do something, you'll find a way. If you don't, you'll find an excuse. - ***Jim Rohn***`,
  `You miss 100% of the shots you don't take.' - ***Wayne Gretzky***`,
  `Believe you can and you're halfway there. - ***Theodore Roosevelt***`,
  'The future depends on what you do today. - ***Mahatma Gandhi***',
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - ***Steve Jobs***',
  'Success is not the key to happiness. Happiness is the key to success. - ***Albert Schweitzer***',
  `I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - ***Jimmy Dean***`,
  'The harder the conflict, the greater the triumph. - ***George Washington***',
  'The best way to predict the future is to create it. - ***Peter Drucker***',
  `Don't watch the clock; do what it does. Keep going.' - ***Sam Levenson***`,
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - ***Christian D. Larson***',
  'The secret of getting ahead is getting started. - ***Mark Twain***',
  `Don't be afraid to give up the good to go for the great. - ***John D. Rockefeller***`,
  'The only person you are destined to become is the person you decide to be. - ***Ralph Waldo Emerson***',
  `Your time is limited, don't waste it living someone else's life. - ***Steve Jobs***`,
  'Dream big and dare to fail. - ***Norman Vaughan***',
  'The best revenge is massive success. - ***Frank Sinatra***',
  `Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - ***Roy T. Bennett***`,
  'Success is not in what you have, but who you are. - ***Bo Bennett***',
  'In the middle of every difficulty lies opportunity. - ***Albert Einstein***',
  'If you want to achieve greatness, stop asking for permission. - ***Anonymous***',
  'You are never too old to set another goal or to dream a new dream. - ***C.S. Lewis***',
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  'If you are not willing to risk the usual, you will have to settle for the ordinary. - ***Jim Rohn***',
  `Don't be afraid to stand for what you believe in, even if that means standing alone. - ***Andy Biersack***`,
  'Success usually comes to those who are too busy to be looking for it. - ***Henry David Thoreau***',
  'The more I want to get something done, the less I call it work. - ***Richard Bach***',
  `Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - ***Roy T. Bennett***`,
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  `Don't be afraid to give up the good to go for the great. - ***John D. Rockefeller***`,
  'The best way to predict the future is to create it. - ***Peter Drucker***',
  'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - ***Steve Jobs***',
  'The harder the conflict, the greater the triumph. - ***George Washington***',
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - ***Christian D. Larson***',
  `If you really want to do something, you'll find a way. If you don't, you'll find an excuse. - ***Jim Rohn***`,
  'Success is not the key to happiness. Happiness is the key to success. - ***Albert Schweitzer***',
  'The only person you are destined to become is the person you decide to be. - ***Ralph Waldo Emerson***',
  'The secret of getting ahead is getting started. - ***Mark Twain***',
  `Believe you can and you're halfway there. - ***Theodore Roosevelt***`,
  `Your time is limited, don't waste it living someone else's life. - ***Steve Jobs***`,
  'Dream big and dare to fail. - ***Norman Vaughan***',
  'The best revenge is massive success. - ***Frank Sinatra***',
  `Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - ***Roy T. Bennett***`,
  'Success is not in what you have, but who you are. - ***Bo Bennett***',
  'If you want to achieve greatness, stop asking for permission. - ***Anonymous***',
  'You are never too old to set another goal or to dream a new dream. - ***C.S. Lewis***',
  'In the middle of every difficulty lies opportunity. - ***Albert Einstein***',
  'The only limit to our realization of tomorrow will be our doubts of today. - ***Franklin D. Roosevelt***',
  'If you are not willing to risk the usual, you will have to settle for the ordinary. - ***Jim Rohn***',
  `Don't be afraid to stand for what you believe in, even if that means standing alone. - ***Andy Biersack***`,
  'Success usually comes to those who are too busy to be looking for it. - ***Henry David Thoreau***',
  'The more I want to get something done, the less I call it work. - ***Richard Bach***',
  'The only way to do great work is to love what you do. - ***Steve Jobs***',
  `Don't watch the clock; do what it does. Keep going. - ***Sam Levenson***`,
  'The road to success and the road to failure are almost exactly the same. - ***Colin R. Davis***',
  'The future depends on what you do today. - ***Mahatma Gandhi***',
  `You miss 100% of the shots you don't take.' - ***Wayne Gretzky***`,
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - ***Christian D. Larson***',
  'The secret of getting ahead is getting started. - ***Mark Twain***',
  'Success is not the key to happiness. Happiness is the key to success. - ***Albert Schweitzer***',
  `I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - ***Jimmy Dean***`,
  'The harder the conflict, the greater the triumph. - ***George Washington***',
  'The best way to predict the future is to create it. - ***Peter Drucker***',
  `Don't watch the clock; do what it does. Keep going. - ***Sam Levenson***`,
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - ***Christian D. Larson***',
  'The secret of getting ahead is getting started. - ***Mark Twain***',
  `Don't be afraid to give up the good to go for the great. - ***John D. Rockefeller***`,
];

module.exports = { dailyQuotes };