const titulosBuenosDias = [ // An array with all the titles for the "saludos-buenos-dias" command
  'Un nuevo día ha amanecido',
  'Comienza el día con energía',
  'Saludos matutinos',
  'Despierta con una sonrisa',
  'Bienvenido al amanecer',
  'Empieza el día con buen pie',
  'Que tengas un día brillante',
  '¡Hola mundo, aquí vamos de nuevo!',
  '¡Arriba y adelante!',
  'Un nuevo día lleno de oportunidades',
  'La mejor manera de empezar el día',
  'Un día fresco y lleno de posibilidades',
  'Buen día, buen inicio',
  'Iniciando un nuevo ciclo diario',
  'Un día para ser feliz',
  'Hoy es un gran día para lograr tus metas',
  'La luz del sol te saluda',
  'Empieza el día con una actitud positiva',
  'Un día lleno de potencial',
  'Comienza tu día con una mente clara',
  'Aprovecha al máximo cada día',
  'La mejor forma de empezar tu día',
  'Un día más para ser feliz',
  'Bienvenido al nuevo día',
  'Un nuevo amanecer, una nueva oportunidad',
  'La mejor forma de comenzar el día es con una sonrisa',
  'Un día lleno de alegría y entusiasmo',
  'El día es tuyo, hazlo tuyo',
  'Levántate y brilla',
  'Que tengas un día lleno de logros',
  '¡Que tengas un día grandioso!',
  'Aprovecha cada segundo del día',
  'Un nuevo día lleno de esperanza',
  'La mejor forma de empezar el día es con gratitud',
  'Un día lleno de promesas',
  'Que el sol te ilumine en este día',
  'Un nuevo día, una nueva oportunidad para ser feliz',
  'Un día lleno de maravillas',
  'Un día lleno de aventuras',
  'Que tengas un día lleno de bendiciones',
  'El mejor día es hoy',
  'El comienzo de un día exitoso',
  'Aprovecha el día al máximo',
  'Un nuevo día para aprender y crecer',
  'Comienza tu día con una mente positiva',
  'Despierta y haz que suceda',
  'Un nuevo día, una nueva aventura',
  'Que tengas un día lleno de inspiración',
  'La vida te regala un nuevo día, disfrútalo',
  'Un nuevo día, una nueva oportunidad para ser tu mejor versión',
];

module.exports = titulosBuenosDias; // exports the array, allowing it to be used inside the command
