const refranesBuenosDias = [ // An array with all the description text for the "saludos-buenos-dias" command
  'Al que madruga, Dios lo ayuda.',
  'El que madruga, encuentra la felicidad en la mañana.',
  'Madruga y verás milagros.',
  'Madrugar es de sabios.',
  'El que madruga, coge agua fresca en la fuente.',
  'Madruga y tendrás un día de ventaja.',
  'A quien madruga, Dios lo ayuda y el diablo no lo alcanza.',
  'Madrugar es saludable para el cuerpo y la mente.',
  'Madruga como el sol y brillarás como él.',
  'Madrugar es el primer paso hacia el éxito.',
  'Al que madruga, la vida le sonríe.',
  'Madrugar es el secreto de la productividad.',
  'Madrugar te permite disfrutar de la tranquilidad del amanecer.',
  'Madrugar es un hábito de triunfadores.',
  'Madrugar es la clave para aprovechar al máximo el día.',
  'Madrugar te da tiempo para reflexionar y planear tu día.',
  'El que madruga, encuentra la felicidad en las cosas simples.',
  'Madrugar te hace más eficiente en todo lo que haces.',
  'Madrugar te da tiempo para hacer ejercicio y cuidar tu salud.',
  'Madrugar te permite llegar temprano y evitar el tráfico.',
  'Madrugar es la mejor manera de comenzar el día con energía.',
  'Madrugar te ayuda a cumplir tus metas y objetivos.',
  'Madrugar te da tiempo para disfrutar de un buen desayuno.',
  'Madrugar es la clave para la disciplina y el éxito a largo plazo.',
  'Madrugar es una forma de demostrarte a ti mismo que eres fuerte y comprometido.',
  'El que madruga, encuentra la paz en la quietud del amanecer.',
  'Madrugar es una oportunidad para ser agradecido por un nuevo día.',
  'Madrugar te permite apreciar la belleza de la naturaleza al amanecer.',
  'Madrugar es la mejor forma de evitar la procrastinación.',
  'Madrugar te ayuda a aprovechar mejor el tiempo.',
  'El que madruga, vive más y mejor.',
  'Madrugar es la mejor manera de tener el control del día.',
  'Madrugar te da tiempo para leer y aprender algo nuevo.',
  'Madrugar es el mejor antídoto contra el estrés.',
  'El que madruga, tiene más oportunidades para aprender y crecer.',
  'Madrugar te permite ahorrar tiempo y dinero.',
  'Madrugar es la clave para una vida equilibrada.',
  'Madrugar te ayuda a ser más organizado y productivo.',
  'El que madruga, disfruta de la tranquilidad del amanecer.',
  'Madrugar te da tiempo para meditar y conectarte contigo mismo.',
  'Madrugar te permite tener más tiempo para pasar con tu familia.',
  'Madrugar es una forma de demostrarte a ti mismo que eres capaz de hacer sacrificios para alcanzar tus metas.',
  'El que madruga, recoge los frutos del éxito.',
  'Madrugar te ayuda a ser más creativo e innovador.',
  'Madrugar es una forma de demostrar tu compromiso con tu trabajo o tus estudios.',
  'Madrugar te da tiempo para disfrutar de la belleza de la ciudad antes de que se llene de gente.',
  'El que madruga, tiene más tiempo para hacer lo que le gusta.',
  'Madrugar te permite evitar la prisa y el estrés del último minuto.',
  'Madrugar es una forma de demostrar gratitud por un nuevo día y una nueva oportunidad.',
  'Madrugar te permite tener más tiempo para hacer una diferencia en el mundo.',
];

module.exports = refranesBuenosDias; // exports the array, allowing it to be used inside the command
