const refranesBuenasNoches = [
  'Que descanses plácidamente y sueñes con los angelitos.',
  'Buenas noches, que los sueños te traigan la paz que necesitas.',
  'Que tus sueños sean tan dulces como tú lo eres.',
  'Que la noche te traiga el descanso que necesitas para un nuevo amanecer.',
  'Que la noche te traiga la tranquilidad que necesitas para afrontar un nuevo día.',
  'Que la noche te traiga el silencio necesario para que descanses en paz.',
  'Que la noche te envuelva con su manto de estrellas y te proteja mientras duermes.',
  'Que la noche te traiga el descanso que mereces después de un día duro de trabajo.',
  'Buenas noches, que tus sueños sean tan grandes como tus metas.',
  'Que la noche te traiga la felicidad que necesitas para seguir adelante.',
  'Que la noche te traiga el amor que mereces.',
  'Buenas noches, que tus sueños sean tan hermosos como lo es tu alma.',
  'Que la noche te traiga el descanso que necesitas para enfrentar los nuevos desafíos.',
  'Que la noche te traiga la paz que necesitas para descansar.',
  'Que la noche te traiga la serenidad que necesitas para afrontar los nuevos retos.',
  'Buenas noches, que los sueños te lleven a lugares maravillosos.',
  'Que la noche te traiga el sosiego que necesitas para relajarte.',
  'Que la noche te traiga el descanso que mereces después de un día lleno de logros.',
  'Buenas noches, que tus sueños te lleven al éxito.',
  'Que la noche te traiga el alivio que necesitas después de un día difícil.',
  'Que la noche te traiga el confort que necesitas para dormir tranquilo.',
  'Que la noche te traiga la seguridad que necesitas para dormir sin preocupaciones.',
  'Que la noche te traiga el descanso que necesitas para renovarte.',
  'Buenas noches, que tus sueños sean tan grandes como tus anhelos.',
  'Que la noche te traiga el consuelo que necesitas después de un día difícil.',
  'Que la noche te traiga el descanso que mereces después de un día lleno de emociones.',
  'Que la noche te traiga el sosiego que necesitas para meditar.',
  'Que la noche te traiga el descanso que necesitas para fortalecerte.',
  'Que la noche te traiga la esperanza que necesitas para seguir adelante.',
  'Buenas noches, que tus sueños te lleven a lugares mágicos.',
  'Que la noche te traiga el descanso que necesitas para sanar.',
  'Que la noche te traiga la fuerza que necesitas para superar los obstáculos.',
  'Que la noche te traiga la paz que necesitas para afrontar los nuevos desafíos.',
  'Que la noche te traiga el equilibrio que necesitas para vivir en armonía.',
  'Que la noche te traiga la paz que necesitas para descansar.',
  'Que tus sueños sean dulces como la miel y tus preocupaciones se disipen como el rocío.',
  'Que la luna te guíe hacia el descanso que mereces.',
  'Que los ángeles te cuiden mientras duermes.',
  'Que la noche te brinde un descanso reparador para que puedas afrontar el día con energía renovada.',
  'Que la oscuridad de la noche te envuelva en un manto de tranquilidad y serenidad.',
  'Que el silencio de la noche te permita escuchar la voz de tu corazón.',
  'Que la noche te brinde la oportunidad de descansar y renovar tus fuerzas.',
  'Que la noche te traiga paz y descanso para que puedas comenzar el nuevo día con alegría y energía.',
  'Que los ángeles te cubran con sus alas mientras duermes.',
  'Que la luna te dé su brillo y te cubra con su luz en esta noche oscura.',
  'Que tus sueños te lleven a lugares mágicos y te hagan sentir vivo.',
  'Que el descanso de esta noche te prepare para un nuevo día lleno de aventuras.',
  'Que la oscuridad de la noche te permita ver la belleza en las pequeñas cosas.',
  'Que los pensamientos positivos te acompañen en tu sueño y te brinden paz y felicidad.',
  'Que la noche te traiga tranquilidad y paz, para que puedas tener un sueño profundo y reparador.',
];

module.exports = refranesBuenasNoches;
