const titulosBuenasNoches = [
  'El descanso es el mejor aliado del éxito',
  'La noche es un buen momento para reflexionar',
  'Descansa bien para empezar el día con energía',
  'La noche es un misterio por descubrir',
  'Un sueño reparador es la clave del bienestar',
  'La oscuridad no es nada comparada con la luz que llevas dentro',
  'Deja que tus preocupaciones se vayan con el sueño',
  'Que las estrellas te guíen hacia tus sueños',
  'No te preocupes, mañana será otro día',
  'La noche es el lienzo donde se pinta el día siguiente',
  'Descansa en paz, despierta con fuerza',
  'Agradece lo que pasó hoy, prepara lo que vendrá mañana',
  'El sueño es la recompensa del trabajo bien hecho',
  'La noche es un tiempo de descanso y sanación',
  'Que la noche te traiga la paz que necesitas',
  'Cada noche es una nueva oportunidad para soñar',
  'No temas a la oscuridad, tu luz interior siempre brillará',
  'La noche es un recordatorio de que todo tiene un final y un nuevo comienzo',
  'Que la tranquilidad de la noche te acompañe siempre',
  'La noche es el momento perfecto para dejar ir lo que no te hace bien',
  'Que la luna te traiga su suave luz y sus misterios',
  'La noche es el tiempo de los sueños, de la imaginación y la creación',
  'Descansa tu cuerpo, alimenta tu alma',
  'La noche es un tesoro por descubrir, con infinitas posibilidades',
  'La noche es el mejor momento para conectarte contigo mismo',
  'Que tus sueños sean más grandes que tus miedos',
  'El sueño es el mejor antídoto contra el estrés',
  'La noche es una oportunidad para resetear, recargar y renovar',
  'El descanso es el combustible para la vida',
  'Que la noche te brinde la calma que necesitas para enfrentar lo que venga',
  'La noche es una pausa en la que el mundo se detiene para que descanses',
  'La noche es un tiempo para nutrir tu cuerpo y mente',
  'Que la oscuridad te haga apreciar la luz aún más',
  'La noche es el momento para agradecer por todo lo que tienes',
  'Que tus sueños sean la semilla de tu futuro',
  'La noche es un abrazo de descanso y confort',
  'La noche es el mejor momento para abrazar a tus seres queridos',
  'Que la noche te permita soltar tus preocupaciones y enfocarte en lo positivo',
  'La noche es un espejo que refleja tus pensamientos y emociones',
  'La noche es el laboratorio donde se crean los grandes sueños',
  'Que la noche te ayude a encontrar la claridad que necesitas',
  'La noche es el camino para llegar a tus metas y objetivos',
  'Descansa bien y sueña con los angelitos',
  'Que tus sueños sean más dulces que la miel',
  'Cerrando los ojos al mundo, abriendo el corazón al descanso',
  'Las estrellas te acompañan en tus sueños',
  'Que el silencio de la noche te traiga paz y tranquilidad',
  'Que el cansancio se vaya y el sueño llegue',
  'No te preocupes por nada, la noche cuidará de ti',
  'La noche te regala su manto oscuro para que descanses',
  'Que los sueños se hagan realidad en el mañana',
];

module.exports = titulosBuenasNoches;
